ccflags-$(CONFIG_HAS_TM4C123XX_SDK) += -D$(COMPILER)
# Need to build prcm and utils for PRCMCC3220MCUInit, which is not in ROM
obj-$(CONFIG_HAS_TM4C123XX_SDK) += tm4c123xx/source/driverlib/gpio.o
#obj-$(CONFIG_HAS_TM4C123XX_SDK) += tm4c123xx/source/driverlib/gpio.o
#obj-$(CONFIG_HAS_TM4C123XX_SDK) += tm4c123xx/source/driverlib/gpio.o
