ifdef CONFIG_HAS_TM4C12X_SDK
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/ek-tm4c12x/source
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/ek-tm4c12x/source/inc
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/ek-tm4c12x/source/driverlib
KBUILD_CFLAGS += -DTARGET_IS_BLIZZARD_RA1
endif # CONFIG_HAS_TM4C12X_SDK
