ifdef CONFIG_HAS_TM4C12X_SDK
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/ek-tm4c12x/source
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/ek-tm4c12x/source/inc
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/ek-tm4c12x/source/driverlib
endif # CONFIG_HAS_TM4C12X_SDK
