obj-$(CONFIG_HAS_MCUX) += nxp/mcux/
obj-$(CONFIG_QMSI_BUILTIN) += qmsi/
obj-$(CONFIG_HAS_STM32CUBE) += st/stm32cube/
obj-$(CONFIG_HAS_CC3220SDK) += ti/simplelink/
obj-$(CONFIG_HAS_TM4C123XX_SDK) += ti/ek-tm4c12x/ek-tm4c123xx/
obj-$(CONFIG_HAS_NORDIC_HAL) += nordic/
obj-$(CONFIG_HAS_NORDIC_DRIVERS) += nordic/drivers/
